apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nemo-argo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Charis-Trantas/NEMO_ARGOCD.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: nemo-argo

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
