apiVersion: apps/v1
kind: Deployment
metadata:
  name: nemo-argo
spec:
  selector:
    matchLabels:
      app: nemo-argo
  replicas: 1
  template:
    metadata:
      labels:
        app: nemo-argo
    spec:
      containers:
      - name: nemo-argo
        image: charist/argo_test:test-1
